# CMake generated Testfile for 
# Source directory: C:/Development/op3d_active/proj-6.0.0/test/unit
# Build directory: C:/Development/op3d_active/proj-6.0.0/msvc/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_pj_transform_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;78;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_pj_transform_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;78;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_pj_transform_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;78;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_pj_transform_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/proj_pj_transform_test.exe")
  set_tests_properties(proj_pj_transform_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;78;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_pj_transform_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_errno_string_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;86;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_errno_string_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;86;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_errno_string_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;86;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_errno_string_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;86;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_errno_string_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_angular_io_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;94;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_angular_io_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;94;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_angular_io_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;94;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_angular_io_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;94;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_angular_io_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_context_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;102;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_context_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;102;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_context_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;102;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_context_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;102;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_context_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pj_phi2_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;113;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pj_phi2_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;113;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pj_phi2_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;113;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pj_phi2_test "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/pj_phi2_test.exe")
  set_tests_properties(pj_phi2_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;113;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(pj_phi2_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_test_cpp_api "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;131;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_test_cpp_api "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;131;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_test_cpp_api "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;131;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_test_cpp_api "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;131;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_test_cpp_api NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gie_self_tests "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Debug/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;139;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gie_self_tests "C:/Development/op3d_active/proj-6.0.0/msvc/bin/Release/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;139;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(gie_self_tests "C:/Development/op3d_active/proj-6.0.0/msvc/bin/MinSizeRel/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;139;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(gie_self_tests "C:/Development/op3d_active/proj-6.0.0/msvc/bin/RelWithDebInfo/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;139;add_test;C:/Development/op3d_active/proj-6.0.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(gie_self_tests NOT_AVAILABLE)
endif()
subdirs("../../googletest-build")
